# Docker compose for multi-org-ca-1
#DEV_MODE_DEV
version: '2'

networks:
  farmersorgu:

services:
  

  # Farmersorg peer1
  farmersorg-peer1.couchdb:
    container_name: farmersorg-peer1.couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "5984:5984"
    networks:
      - farmersorgu

  farmersorg-peer1.farmersorg.com:
    container_name: farmersorg-peer1.farmersorg.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=farmersorg-peer1.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - farmersorg-peer1.couchdb

  # Logistics peer1
  logistics-peer1.couchdb:
    container_name: logistics-peer1.couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "6984:5984"
    networks:
      - farmersorgu

  logistics-peer1.logistics.com:
    container_name: logistics-peer1.logistics.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=logistics-peer1.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - logistics-peer1.couchdb
    
  # Srienterprices peer1
  srienterprices-peer1.couchdb:
    container_name: srienterprices-peer1.couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "7984:5984"
    networks:
      - farmersorgu

  srienterprices-peer1.srienterprices.com:
    container_name: srienterprices-peer1.srienterprices.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=srienterprices-peer1.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - srienterprices-peer1.couchdb      
    
  # Priceauthority peer1
  priceauthority-peer1.couchdb:
    container_name: priceauthority-peer1.couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "8984:5984"
    networks:
      - farmersorgu

  priceauthority-peer1.priceauthority.com:
    container_name: priceauthority-peer1.priceauthority.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=priceauthority-peer1.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - priceauthority-peer1.couchdb       