# Docker compose for multi-org-ca-1
#DEV_MODE_NET
version: '2'

networks:
  farmersorgu:

services:
  # Orderer
  orderer.farmersorg.com:
    container_name: orderer.farmersorg.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      # - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=orderer.farmersorg.com
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/genesis/farmersorgu-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/msp
      - ORDERER_FILELEDGER_LOCATION=/var/ledger
    working_dir: $HOME
    command: orderer
    volumes:
    # Folder with genesis block
    - ${PWD}/../config:/var/hyperledger/genesis
    # Map the folder with MSP for orderer
    - ${PWD}/../crypto/crypto-config/ordererOrganizations/farmersorg.com/orderers/orderer.farmersorg.com/msp:/var/hyperledger/msp
    # Map the current folder to cfg
    - ${PWD}/../config:/var/hyperledger/config
    - ${HOME}/ledgers/orderer.farmersorg.com:/var/ledger
    ports:
      - 6050:6050
    networks:
      - farmersorgu

  # Farmersorg peer1
  farmersorg-peer1.farmersorg.com:
    container_name: farmersorg-peer1.farmersorg.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      # - CORE_LOGGING_LEVEL=debug
      - FABRIC_LOGGING_SPEC=DEBUG

      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_farmersorgu

      - CORE_PEER_ID=farmersorg-peer1.farmersorg.com
      # - CORE_PEER_LISTENADDRESS=pn-peer1.pn.com:6051
      - CORE_PEER_ADDRESS=farmersorg-peer1.farmersorg.com:6051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=farmersorg-peer1.farmersorg.com:6051
      # - CORE_PEER_ADDRESS=0.0.0.0:6051
      # - CORE_PEER_GOSSIP_EXTERNALENDPOINT=0.0.0.0:6051

      - CORE_PEER_LOCALMSPID=FarmersorgMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_ENABLED=false
      # - CORE_PEER_GOSSIP_USELEADERELECTION=true
      # - CORE_PEER_GOSSIP_ORGLEADER=false
      # - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_FILESYSTEMPATH=/var/ledger
      # - CORE_PEER_ADDRESS=0.0.0.0
    working_dir: $HOME
    # command: peer node start --peer-chaincodedev=true
    command: peer node start

    volumes:
      # Folder with channel create tx file
      - ${PWD}/../config:/var/hyperledger/channeltx
      # Map the folder with MSP for Peer
      - ${PWD}/../crypto/crypto-config/peerOrganizations/farmersorg.com/peers/farmersorg-peer1/msp:/var/hyperledger/msp
      # Map the current folder to cfg
      - ${PWD}/../config:/var/hyperledger/config
      - /var/run/:/host/var/run/
      # Ledger folder for the peer
      - ${HOME}/ledgers/farmersorg-peer1.farmersorg.com/:/var/ledger
    depends_on: 
      - orderer.farmersorg.com
    ports:
      - 6051:6051
      - 6052:6052
      - 6053:6053
    networks:
      - farmersorgu

  # Logistics peer1
  logistics-peer1.logistics.com:
    container_name: logistics-peer1.logistics.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      # - CORE_LOGGING_LEVEL=debug
      - FABRIC_LOGGING_SPEC=DEBUG

      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_farmersorgu

      - CORE_PEER_ID=logistics-peer1.logistics.com
      - CORE_PEER_ADDRESS=logistics-peer1.logistics.com:7051
      # - CORE_PEER_LISTENADDRESS=logistics-peer1.logistics.com:7051
      - CORE_PEER_LISTENADDRESS=logistics-peer1.logistics.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=logistics-peer1.logistics.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=logistics-peer1.logistics.com:7051
      - CORE_PEER_LOCALMSPID=LogisticsMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_ENABLED=false
      # - CORE_PEER_GOSSIP_USELEADERELECTION=true
      # - CORE_PEER_GOSSIP_ORGLEADER=false
      # - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_FILESYSTEMPATH=/var/ledger
    working_dir: $HOME
    # command: peer node start --peer-chaincodedev=true
    command: peer node start

    volumes:
      # Folder with channel create tx file
      - ${PWD}/../config:/var/hyperledger/channeltx
      # Map the folder with MSP for Peer
      - ${PWD}/../crypto/crypto-config/peerOrganizations/logistics.com/peers/logistics-peer1/msp:/var/hyperledger/msp
      # Map the current folder to cfg
      - ${PWD}/../config:/var/hyperledger/config
      - /var/run/:/host/var/run/
      # Ledger folder for the peer
      - ${HOME}/ledgers/logistics-peer1.logistics.com:/var/ledger
    depends_on: 
      - orderer.farmersorg.com
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    networks:
      - farmersorgu

  # Srienterprices peer1
  srienterprices-peer1.srienterprices.com:
    container_name: srienterprices-peer1.srienterprices.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      # - CORE_LOGGING_LEVEL=debug
      - FABRIC_LOGGING_SPEC=DEBUG

      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_farmersorgu

      - CORE_PEER_ID=srienterprices-peer1.srienterprices.com
      - CORE_PEER_ADDRESS=srienterprices-peer1.srienterprices.com:8051
      # - CORE_PEER_LISTENADDRESS=srienterprices-peer1.srienterprices.com:8051
      - CORE_PEER_LISTENADDRESS=srienterprices-peer1.srienterprices.com:8051
      - CORE_PEER_CHAINCODELISTENADDRESS=srienterprices-peer1.srienterprices.com:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=srienterprices-peer1.srienterprices.com:8051
      - CORE_PEER_LOCALMSPID=SrienterpricesMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_ENABLED=false
      # - CORE_PEER_GOSSIP_USELEADERELECTION=true
      # - CORE_PEER_GOSSIP_ORGLEADER=false
      # - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_FILESYSTEMPATH=/var/ledger
    working_dir: $HOME
    # command: peer node start --peer-chaincodedev=true
    command: peer node start

    volumes:
      # Folder with channel create tx file
      - ${PWD}/../config:/var/hyperledger/channeltx
      # Map the folder with MSP for Peer
      - ${PWD}/../crypto/crypto-config/peerOrganizations/srienterprices.com/peers/srienterprices-peer1/msp:/var/hyperledger/msp
      # Map the current folder to cfg
      - ${PWD}/../config:/var/hyperledger/config
      - /var/run/:/host/var/run/
      # Ledger folder for the peer
      - ${HOME}/ledgers/srienterprices-peer1.srienterprices.com:/var/ledger
    depends_on: 
      - orderer.farmersorg.com
    ports:
      - 8051:8051
      - 8052:8052
      - 8053:8053
    networks:
      - farmersorgu
    
  # Priceauthority peer1
  priceauthority-peer1.priceauthority.com:
    container_name: priceauthority-peer1.priceauthority.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      # - CORE_LOGGING_LEVEL=debug
      - FABRIC_LOGGING_SPEC=DEBUG

      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_farmersorgu

      - CORE_PEER_ID=priceauthority-peer1.priceauthority.com
      - CORE_PEER_ADDRESS=priceauthority-peer1.priceauthority.com:9051
      # - CORE_PEER_LISTENADDRESS=priceauthority-peer1.priceauthority.com:9051
      - CORE_PEER_LISTENADDRESS=priceauthority-peer1.priceauthority.com:9051
      - CORE_PEER_CHAINCODELISTENADDRESS=priceauthority-peer1.priceauthority.com:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=priceauthority-peer1.priceauthority.com:9051
      - CORE_PEER_LOCALMSPID=PriceauthorityMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_ENABLED=false
      # - CORE_PEER_GOSSIP_USELEADERELECTION=true
      # - CORE_PEER_GOSSIP_ORGLEADER=false
      # - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_FILESYSTEMPATH=/var/ledger
    working_dir: $HOME
    # command: peer node start --peer-chaincodedev=true
    command: peer node start
     
    volumes:
      # Folder with channel create tx file
      - ${PWD}/../config:/var/hyperledger/channeltx
      # Map the folder with MSP for Peer
      - ${PWD}/../crypto/crypto-config/peerOrganizations/priceauthority.com/peers/priceauthority-peer1/msp:/var/hyperledger/msp
      # Map the current folder to cfg
      - ${PWD}/../config:/var/hyperledger/config
      - /var/run/:/host/var/run/
      # Ledger folder for the peer
      - ${HOME}/ledgers/priceauthority-peer1.priceauthority.com:/var/ledger
    depends_on: 
      - orderer.farmersorg.com
    ports:
      - 9051:9051
      - 9052:9052
      - 9053:9053
    networks:
      - farmersorgu

  # tools:
  #   container_name: tools
  #   command: /bin/bash
  #   image: hyperledger/fabric-tools:$IMAGE_TAG
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     - GOPATH=/opt/gopath
  #     - CORE_PEER_ADDRESS=acme-peer1.acme.com:7051
  #     - CORE_PEER_LOCALMSPID=AcmeMSP
  #     - FABRIC_CFG_PATH=/var/hyperledger/config
  #     - CORE_PEER_TLS_ENABLED=false
  #     - CORE_LOGGING_LEVEL=debug
  #   working_dir: /opt/scripts
  #   volumes:
  #     - ${GOPATH}:/opt/gopath
  #     # Folder with channel create tx file
  #     - ${PWD}/../artefacts:/var/hyperledger/channeltx
  #     # Map the folder to root of all Fabric CA Client crypto
  #     - ${PWD}/../crypto/crypto-config/peerOrganizations:/var/hyperledger/crypto
  #     # Map the current folder to cfg
  #     - ${PWD}/../config:/var/hyperledger/config
  #     # VM docker stream folder mapping
  #     - /var/run/:/host/var/run/
  #     # Map the bins folder
  #     - ${PWD}/../scripts:/opt/scripts
  #     # Map the nodechaincode folder
  #     - ${PWD}/../tests:/opt/chaincode
  #   networks:
  #     - airline
  
  # Postgres
  # postgresql:
  #   container_name: postgresql
  #   image: postgres:9.5
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
      
  #   working_dir: $HOME
  #   volumes:
  #   # Folder with genesis block
  #   #- ${PWD}:/etc/postgresql/9.5/main
  #   - $PWD/explorer/bins:/home/vagrant/bins
  #   - /var/run/postgresql:/var/run/postgresql
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - airline
  
  # explorer:
  #   container_name: explorer
  #   image: acloudfan/hlf-explorer
  #   environment:
  #     - DATABASE_PASSWORD=postgres
  #     - DATABASE_HOST=postgresql
  #   volumes:
  #     - $PWD/explorer/bins:/home/vagrant/bins
  #     - $PWD/../crypto:/vagrant/network/crypto
  #     - /var/run/postgresql:/var/run/postgresql
  #   ports:
  #     - 8080:8080
  #   depends_on: 
  #     - postgresql
  #   networks:
  #     - airline